### ISSUE TITLE
Undefined variables $ErrNo, $ErrStr and $Data

### ISSUE THREAD

**Issue by hulyman** [xPaw/PHP-Source-Query-Class#34]
https://github.com/xPaw/PHP-Source-Query-Class/blob/master/SourceQuery/Socket.class.php#L47

https://github.com/xPaw/PHP-Source-Query-Class/blob/master/SourceQuery/Socket.class.php#L142

**Comment by Kubo2** [comment]
@hulyman 
> But the variables does not defined before

Yeah, but they're passed [by `&`reference](http://php.net//language.references.pass) to a function. In PHP, variable starts its life when you first use it - and those variables are first being used in the function call where they are passed by reference, with default value `null`, supposed to be modified by a function.
