### ISSUE TITLE
Rcon command response keeps getting downloaded down in a file.

### ISSUE THREAD

**Issue by Dunkstormen** [xPaw/PHP-Source-Query-Class#37]
Rcon command response keeps getting downloaded down in a file.

http://gyazo.com/4146ef7f5568a536283c1e015abaa234

And it echos:

7374 7269 6e67 2831 3729 2022 436f 6e73
6f6c 653a 2068 656c 6c6f 0a00 0022 0a

**Comment by Kubo2** [comment]
@Dunkstormen And how does look your code?

**Comment by DioJoestar** [comment]
Same here, without any change on the code.

**Comment by Dunkstormen** [comment]
Just the default code, havent changed anything else than the connection settings.

**Comment by xPaw** [comment]
Is your webserver misconfigured or something? It's hard to tell you anything if you don't provide any information. Is the RCON command actually executed on the server? If yes, have you tried a different command?

**Comment by sekjun9878** [comment]
Could it be due to the header `text/plain` being set and Chrome downloading it as a text file?

**Comment by xPaw** [comment]
... that shouldn't happen?

**Comment by DioJoestar** [comment]
It works now.
> // For the sake of this example
> Header( 'X-Content-Type-Options: nosniff' );

**Comment by Mechazawa** [comment]
Change the header to the following to support older versions of FireFox. It forces FireFox to display the content as the supplied mime-type.
```http
Content-Type: text/plain; imeanit=yes
```
Can't be bothered to make a pull request for this though.
