### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by xPaw** [xPaw/PHP-Source-Query-Class#38]
I want to change to the license to `LGPL-2.1` to allow commercial use, and a generally better license than creative commons.

Before doing so, I ask people that contributed to this repository before, to see if they agree with this.
@Kubo2 @sekjun9878 You fine with that?

**Comment by sekjun9878** [comment]
I agree with this change and allow all portions of my contributed code until now to be sublicensed to LGPL v2.1.

**Comment by Sk3y** [comment]
i agree :)

**Comment by Mechazawa** [comment]
LGPL is nice except for the disclose source clause which makes it a pain to use. It requires the user to disclose the source code of the library even if it has been modified.

> a) Accompany the work with the complete corresponding machine-readable source code for the Library including whatever changes were used in the work (which must be distributed under Sections 1 and 2 above); and, if the work is an executable linked with the Library, with the complete machine-readable "work that uses the Library", as object code and/or source code, so that the user can modify the Library and then relink to produce a modified executable containing the modified Library. (It is understood that the user who changes the contents of definitions files in the Library will not necessarily be able to recompile the application to use the modified definitions.)

**Comment by sekjun9878** [comment]
@Mechazawa I agree, an MIT or BSD would be great but at least the LGPL is a lot better than CC BY-NC-SA!

**Comment by Kubo2** [comment]
@xPaw Yeah, I agree with LGPL, of course :-)
