### ISSUE TITLE
Player id always return 0?

### ISSUE THREAD

**Issue by pede** [xPaw/PHP-Source-Query-Class#41]
Why do the player id always return 0?

Already commeted in SourceQuery.class.php line 401: 
"$Player[ 'Id' ]    = $this->Buffer->GetByte( ); // PlayerID, is it just always 0?"

Example of my GetPlayers array:

Array
(
[0] => Array
(
[Id] => 0
[Name] => SwagMaster08
[Frags] => 1
[Time] => 4344
[TimeF] => 01:12:24
)

[1] => Array
    (
        [Id] => 0
        [Name] => Olaf
        [Frags] => 0
        [Time] => 4332
        [TimeF] => 01:12:12
    )

[2] => Array
    (
        [Id] => 0
        [Name] => Jesper
        [Frags] => 0
        [Time] => 3951
        [TimeF] => 01:05:51
    )

[3] => Array
    (
        [Id] => 0
        [Name] => Keps
        [Frags] => 0
        [Time] => 1289
        [TimeF] => 21:29
    )

)

Hope you can fix this, Thanks!

**Comment by xPaw** [comment]
Because that's how games implement the protocol, you should bug game developers.
