### ISSUE TITLE
Sporadic Warnings being thrown when unpacking data 

### ISSUE THREAD

**Issue by lps-rocks** [xPaw/PHP-Source-Query-Class#42]
I run a number of L4D2 servers (I'm also incorporating this into a rewrite of HLStatsX (HLStats-php). This seems to be an issue that pops up on a fairly common basis. 

I've been testing this against L4D2 and it seems to happen sporadically. 

```
Invalid argument: Type l: not enough input, need 4, have 0
#0 /var/www/lps.rocks/vendor/xpaw/php-source-query-class/SourceQuery/Buffer.class.php(126): Illuminate\Exception\Handler->handleError()
#1 /var/www/lps.rocks/vendor/xpaw/php-source-query-class/SourceQuery/SourceRcon.class.php(81): SourceQueryBuffer->GetLong()
#2 /var/www/lps.rocks/vendor/xpaw/php-source-query-class/SourceQuery/SourceRcon.class.php(148): SourceQuerySourceRcon->Read()
#3 /var/www/lps.rocks/vendor/xpaw/php-source-query-class/SourceQuery/SourceQuery.class.php(552): SourceQuerySourceRcon->Authorize()
#4 /var/www/lps.rocks/app/models/EngineHL.php(150): SourceQuery->SetRconPassword()
#5 /var/www/lps.rocks/app/models/EngineHL.php(121): EngineHL->rcon()
#6 /var/www/lps.rocks/app/models/EngineHL.php(67): EngineHL->difficulty()
#7 /var/www/lps.rocks/app/models/GameServer.php(52): EngineHL->sync()
#8 /var/www/lps.rocks/app/commands/LogServer.php(73): GameServer::getLive()
```

**Comment by xPaw** [comment]
If it fails on that line, that means server didn't send any data. Perhaps your firewall is doing something funky? Have you tried other servers that aren't L4D2, or on a different host?

**Comment by lps-rocks** [comment]
It's not throwing any timeout errors. No firewall causing problems. I haven't tried other games yet but it seems to be sporadic. It sounds like there is a condition occurring that isn't being accounted for, also it appears there's a lack of data integrity checking in this code. It seems to assume the buffer always holds the correct data. I would suggest that if the buffer is empty that an exception be thrown giving a description of corrupted data and not allowing for a standard PHP call (unpack) to cause a warning.

**Comment by xPaw** [comment]
Yeah it probably should throw if it didn't read anything from socket.

**Comment by lps-rocks** [comment]
Yay more exceptions I can catch! :+1:

**Comment by xPaw** [comment]
By the way, @lps-rocks have you tried increasing timeout?

**Comment by lps-rocks** [comment]
I have, It seems to occur when the server changes maps in the middle of an rcon command being issued (e.g. between challenge / sending command). The server may drop the command since it's changing map.

**Comment by xPaw** [comment]
That would be a reasonable explanation.

**Comment by lps-rocks** [comment]
The strange part is though, I wouldn't expect an empty or corrupted buffer if that was the case.

I'm going to dig into this possibly a bit more and see what is causing the buffer to become corrupted.

**Comment by xPaw** [comment]
There's not much I can do, since it's simply writing and reading from socket.

**Comment by lps-rocks** [comment]
I'll have to go dig into the code (and behavior of rcon) a bit. In theory the buffer shouldn't be empty if it received a packet. If it didn't receive a packet it should be timing out but it's not timing out. It's instead the buffer is shorter than expected.

**Comment by xPaw** [comment]
Buffer is not shorther than expected, it's literally empty because it didn't read anything from socket.

**Comment by lps-rocks** [comment]
After doing your Fread you could check the timed_out property of the stream meta. If it's timed out, throw an exception instead of returning an empty buffer, 

http://php.net/manual/en/function.stream-get-meta-data.php

thoughts?

**Comment by xPaw** [comment]
I don't think that's necessary. The reason there is no error about timeout, is because fread simply stops trying to read after it times out. I already do buffer checks in other places, but simply forgot to do that specifically in SourceRcon causing this error to happen.

**Comment by lps-rocks** [comment]
Okay, I wasn't sure since you brought up the concern of extending timeouts if there was a problem determining the difference between an end of buffer and no response.

**Comment by xPaw** [comment]
You should try testing 00c5a9f234111fff6a97aaa149b551fdb3078bea change.
