### ISSUE TITLE
Two servers on one page

### ISSUE THREAD

**Issue by Prawx** [xPaw/PHP-Source-Query-Class#44]
While trying to query two servers on the same page, I presume all variables override and everything messes up. Both server queries work fine separate, but they do not work at all when on the same page. I tried adding a 2 to the end of every variable in every file for the second server query, that didn't help. I also tried changing the second server's credentials area to this format: 

$sq_server_addr = x.x.x.x;

$sq_server_port = xxxxx;

$sq_timeout     = 1;

$sq_engine      = "SourceQuery :: SOURCE";

but that did not work^
I'm simplying doing this by putting both View.php 's onto one single page, while having two separate /sourcequery folders and files for each query. 
Yet all I get is a blank page either way. Please help! :)

**Comment by xPaw** [comment]
Please don't create issues about your inability to use PHP.

**Comment by Prawx** [comment]
Well, how can I fix it then man?

**Comment by Prawx** [comment]
Isn't that the point of getting support? You don't know how to do something or you are having a problem so you contact the developer. What is your problem, instead of helping me you tell me not to create a support ticket for my "inability of PHP." I am a web developer, I can use PHP, this is a problem I was having with YOUR script, and I was hoping you'd be kind enough to lend me support. Clearly not.

**Comment by Prawx** [comment]
Here I am thinking "Oh I can save time, I don't have to go to the internet or stackoverflow for help, I can ask the friendly developer of the product to help me!" But that's clearly not the case. Did you know that developers who are friendly and helpful to their users gain more popularity and better feedback? I am astonished that you'd just shoot me down like this, rather than just assist me when I am having a problem. Not even a word of advice, you just insult my ability to use PHP and then leave as if it never happened. It could have went better, you could have told me some advice, possibly ANYTHING to assist me with my problem, and I would have thought "oh wow, what a nice developer, I'm going to tell all of my friends about Pavel and recommend him and share about him because he's great. " But now I'm in the mindset of someone who would NOT recommend you to anyone, simply because you refuse to give simple support on github? I am beyond confused with this, as much as I am disappointed.

**Comment by xPaw** [comment]
Releasing a library doesn't mean you're going to get support on it, or making it work for you by holding your hand. If you don't know how to do something, you search on the internet, or ask on stackoverflow.

Provided example scripts are solely for debugging and as you might have guessed, to use as an example. If you're trying to modify them to fit your needs, you're on your own.

The point of issues section existing is to create issues about the library it self, not when you are having problems with modifying the example script.

**Comment by rleathers** [comment]
Prawx rants like yours are the reason unpaid developers stop making their
work public.   Yes ask questions.  Maybe somebody will help you.  But
please don't rant like a spoiled child if you don't get the free help you
seek.  You ruin future development for everyone including yourself.

**Comment by Prawx** [comment]
k

**Comment by Kubo2** [comment]
@Prawx:
> While trying to query two servers on the same page, I presume all variables override and everything messes up.

So pass the parameters to `__construct`or directly and don't assign them to variables.
