### ISSUE TITLE
Arma 3 GetPlayers did not work over a specific amount of players

### ISSUE THREAD

**Issue by axi92** [xPaw/PHP-Source-Query-Class#48]
I play on a Server with 150-200 players but I cant get the players with GetPlayers()
With 74 it works but at the moment we have 149 players and the page is loading extream long (turned up the timeout) but after this time it remains white.

The Server IP is: 37.187.170.178

**Comment by xPaw** [comment]
Just tried it, there are 122 players on the server, and it loads just fine.

**Comment by axi92** [comment]
Hmmm...
I cant understand what I have done wrong?
Maybe you can look over it? https://github.com/axi92/PHP-Source-Query-Class/blob/beta/Example.php
Maybe some apache limits? I just tried it at home.

**Comment by xPaw** [comment]
Your timeout is set to 1 second, but you said page time takes a long time, that doesn't sound right.

**Comment by axi92** [comment]
Yes in this version its 1 but I raised it to 300 and wait for this time but the result was just a white page.
The timeout was always right, it stopped loading after this time.

**Comment by axi92** [comment]
I dont know why but i uploaded the files to my server and there it works perfect: https://black-evolution.de/arma3/Example.php
You can close the issue
