### ISSUE TITLE
Source Server Query to get SteamID or Nick name

### ISSUE THREAD

**Issue by Cludas18** [xPaw/PHP-Source-Query-Class#50]
Hi I was wondering if there was a way to get a players SteamID or in game name (for Garry's Mod) rather than just their Steam name. I've tried using $player['ID'] but as a comment in one of the files says, it just gives 0 or nothing.

 (Posted in the right place this time....)

**Comment by Mechazawa** [comment]
send the rcon command `status` and parse it using the regex `(STEAM_[01]:\d:\d+)`.

**Comment by Cludas18** [comment]
Already done that and it just seems kinda weird, but i figured it works so why not. Thanks.
