### ISSUE TITLE
Example RCON code outputting '&#65533;' characters

### ISSUE THREAD

**Issue by 0xBADC0DEE** [xPaw/PHP-Source-Query-Class#51]
I'm using the exact same code as in RconExample.php.

I'm trying to use this on a Minecraft server.

I'm getting the following output on my local PHP server:

    string(2) "��"

The two "�" characters have a value of "65533".

Any ideas here?

**Comment by xPaw** [comment]
Hm, I think there's 2 extra bytes after data, if I run `help` on my server, it outputs the command, and 2 extra bytes.

As to why you're not getting any data, perhaps you ran a command that doesn't exist (using a modded server?), try `list` command.
