### ISSUE TITLE
Servers problem

### ISSUE THREAD

**Issue by matanasa66** [xPaw/PHP-Source-Query-Class#53]
Hey mister xPaw, I am using your query-class and I encountered some querying issues
for an example
I have 2 servers , both counter strike servers, both are working well. but your query class queries only one of them
the queryable one: 
199.203.35.242:27015
the non-queryable:
212.235.19.205:31333

+ I have tried adding multiple servers and few works, few doesn't.
I don't know why.

**Comment by xPaw** [comment]
Both of these servers are not displaying info in Steam servers window either.
