### ISSUE TITLE
RCON problem with Arma3 server

### ISSUE THREAD

**Issue by m4ss1ve** [xPaw/PHP-Source-Query-Class#54]
hello am using this:

<?php
	require __DIR__ . '/SourceQuery/SourceQuery.class.php';
	
	// For the sake of this example
	Header( 'Content-Type: text/plain' );
	Header( 'X-Content-Type-Options: nosniff' );
	
	// Edit this ->
	define( 'SQ_SERVER_ADDR', 'localhost' );
	define( 'SQ_SERVER_PORT', 27015 );
	define( 'SQ_TIMEOUT',     1 );
	define( 'SQ_ENGINE',      SourceQuery :: SOURCE );
	// Edit this <-
	
	$Query = new SourceQuery( );
	
	try
	{
		$Query->Connect( SQ_SERVER_ADDR, SQ_SERVER_PORT, SQ_TIMEOUT, SQ_ENGINE );
		
		$Query->SetRconPassword( 'my_awesome_password' );
		
		var_dump( $Query->Rcon( 'say hello' ) );
	}
	catch( Exception $e )
	{
		echo $e->getMessage( );
	}
	
	$Query->Disconnect( );

and getting:

Can't connect to RCON server: Connection timed out

query works, i can get info just fine, the password is right am sure port is right as well, not like the query one, any ideas ?

**Comment by xPaw** [comment]
Your answer lies within "Connection timed out". Verify ip/port.

**Comment by m4ss1ve** [comment]
ip/port is correct

**Comment by m4ss1ve** [comment]
if i change SOURCE with GOLDSOURCE am getting bool(false)
dont know if that helps

**Comment by xPaw** [comment]
Did you try adding +1 to the port? I can't remember what, but there was some quirk with Arma 3.

**Comment by m4ss1ve** [comment]
yeah, same error

**Comment by xPaw** [comment]
I don't play Arma 3, so I don't know why it's not working, you're on your own.

**Comment by m4ss1ve** [comment]
ok thank anyway
